server:
  port: 8080
  servlet:
    context-path: /football-standing

football-api-service:
  url: https://apiv3.apifootball.com/
  api-key: 9bb66184e0c8145384fd2cc0f7b914ada57b4e8fd2e4d6d586adcc27c257a978


spring:
  jackson:
    default-property-inclusion: always
